version: '3.8'
services:
  database:
    image: postgres:14
    container_name: ventry-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: M3m23e9ji32
    ports:
      - 5432:5432
    restart: always
    volumes: 
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql

  web-app:
    build: .
    container_name: ventry-app
    environment:
      VENTRY_POSTGRES_DATABASE: ventrydb
      VENTRY_POSTGRES_USERNAME: postgres
      VENTRY_POSTGRES_PASSWORD: M3m23e9ji32
      VENTRY_POSTGRES_HOST: ventry-postgres
      VENTRY_POSTGRES_PORT: 5432
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/Ventry
    working_dir: /usr/src/Ventry
    command: go run .
    depends_on:
      - database
    restart: on-failure
